-- ====================================================
-- JB Beauty Expo 2026 — Supabase Database Setup
-- 在 Supabase SQL Editor 里把这段全部复制粘贴执行
-- ====================================================

-- 1. 产品库存表
create table if not exists items (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text not null,
  category text not null default 'Skincare',
  price numeric(10,2) not null default 0,
  qty integer not null default 0,
  sku text,
  created_at timestamptz default now()
);

-- 2. 顾客订单表
create table if not exists orders (
  id bigint generated by default as identity primary key,
  order_no text not null,
  customer text not null,
  phone text,
  payment text not null default 'cash',
  lines jsonb not null default '[]',
  total numeric(10,2) not null default 0,
  note text,
  created_at timestamptz default now()
);

-- 3. 开启 Realtime（让两个人同步）
alter publication supabase_realtime add table items;
alter publication supabase_realtime add table orders;

-- 4. 允许公开读写（因为是内部用，不需要登录）
alter table items enable row level security;
alter table orders enable row level security;

create policy "Allow all" on items for all using (true) with check (true);
create policy "Allow all" on orders for all using (true) with check (true);

-- 5. 插入示例产品数据
insert into items (name, brand, category, price, qty, sku) values
  ('Laneige Lip Sleeping Mask', 'Laneige', 'Skincare', 79, 48, 'LAN-001'),
  ('NARS Radiant Creamy Concealer', 'NARS', 'Makeup', 165, 12, 'NAR-001'),
  ('Dyson Supersonic Hair Dryer', 'Dyson', 'Haircare', 1899, 5, 'DYS-001'),
  ('Jo Malone Lime Basil & Mandarin', 'Jo Malone', 'Fragrance', 450, 8, 'JOM-001'),
  ('L''Occitane Shea Butter Body Cream', 'L''Occitane', 'Body Care', 129, 32, 'LOC-001'),
  ('Beautyblender Original Sponge', 'Beautyblender', 'Tools & Accessories', 59, 3, 'BLN-001'),
  ('SK-II Facial Treatment Essence', 'SK-II', 'Skincare', 599, 0, 'SKI-001'),
  ('Charlotte Tilbury Pillow Talk Lip', 'Charlotte Tilbury', 'Makeup', 189, 22, 'CTB-001');
